# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: bchaudry <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/12/04 17:33:15 by bchaudry          #+#    #+#              #
#    Updated: 2018/12/04 17:33:17 by bchaudry         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

$(NAME):
	all

all:
	gcc -Wall -Werror -Wextra *.c -o ft_display_file

clean:
	/bin/rm -f *.o

fclean: 
	/bin/rm -f ft_display_file
